# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=2004"]
  - repo: https://github.com/awebdeveloper/pre-commit-tslint/
    rev: "0.0.2" # Use the sha or tag you want to point at
    hooks:
      - id: tslint
        additional_dependencies: ["tslint@5.0.0"]
        args: ["--project", "tsconfig.json", "--type-check"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.6" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
